#!/bin/bash

echo "🔍 VERCEL DEPLOYMENT TROUBLESHOOTING"
echo "====================================="
echo ""
echo "App URL: https://hdjsinsnshsajapaka.vercel.app/"
echo ""
echo "📋 CHECKLIST - Sila check setiap item:"
echo ""

echo "1️⃣  ENVIRONMENT VARIABLES"
echo "   Go to: https://vercel.com/dashboard"
echo "   → Select project: Hdjsinsnshsajapaka"
echo "   → Settings → Environment Variables"
echo ""
echo "   Required variables:"
echo "   [ ] DATABASE_URL = postgresql://neondb_owner:npg_PgQsZS4DeY9F@..."
echo "   [ ] IMGBB_API_KEY = 4042c537845e8b19b443add46f4a859c"
echo "   [ ] VITE_API_URL = /api"
echo ""
echo "   ⚠️  If MISSING: Add them and REDEPLOY"
echo ""

echo "2️⃣  BUILD STATUS"
echo "   Go to: Deployments tab"
echo "   Latest deployment status:"
echo "   [ ] Building..."
echo "   [ ] Ready (green checkmark) ✅"
echo "   [ ] Failed (red X) ❌"
echo ""
echo "   If FAILED: Check build logs for errors"
echo ""

echo "3️⃣  COMMON ISSUES & SOLUTIONS"
echo ""
echo "   Issue A: Blank White Page"
echo "   Possible causes:"
echo "   - Missing environment variables"
echo "   - API connection errors"
echo "   - Build artifacts not deployed"
echo ""
echo "   Solution:"
echo "   a) Open browser DevTools (F12)"
echo "   b) Check Console tab for errors"
echo "   c) Check Network tab for failed requests"
echo ""

echo "   Issue B: 'Cannot GET /api/...'"
echo "   Possible causes:"
echo "   - API routes not deployed"
echo "   - Wrong API_URL configuration"
echo ""
echo "   Solution:"
echo "   - Verify VITE_API_URL=/api in Vercel env vars"
echo "   - Check api/ folder exists in deployment"
echo ""

echo "   Issue C: Database Connection Failed"
echo "   Possible causes:"
echo "   - DATABASE_URL not set or incorrect"
echo "   - Neon database sleeping/inactive"
echo ""
echo "   Solution:"
echo "   - Verify DATABASE_URL is set correctly"
echo "   - Check Neon console: database is active"
echo ""

echo "4️⃣  QUICK DEBUGGING"
echo ""
echo "   Test API endpoint directly:"
echo "   → https://hdjsinsnshsajapaka.vercel.app/api/routes"
echo ""
echo "   Expected response:"
echo "   - If env vars set: JSON with routes data"
echo "   - If missing: JSON with dummy data"
echo "   - If error: Error message"
echo ""

echo "5️⃣  REDEPLOY STEPS"
echo ""
echo "   If you added/changed env vars:"
echo "   a) Go to: Deployments tab"
echo "   b) Click ⋯ (three dots) on latest deployment"
echo "   c) Click 'Redeploy'"
echo "   d) Wait for deployment to complete"
echo ""

echo "==============================================="
echo "📞 WHAT TO CHECK NEXT:"
echo "==============================================="
echo ""
echo "1. Open: https://hdjsinsnshsajapaka.vercel.app/"
echo "2. Press F12 (Open DevTools)"
echo "3. Go to Console tab"
echo "4. Look for RED errors"
echo "5. Screenshot and report what you see"
echo ""
echo "Or:"
echo ""
echo "6. Go to: https://hdjsinsnshsajapaka.vercel.app/api/routes"
echo "7. What do you see? (JSON data, error, blank?)"
echo "8. Report back"
echo ""
echo "==============================================="
